### PR TITLE
re #10 Rm unused deps, update paths for npm3, add npm scripts

### PR DESCRIPTION
**Pull request by kahboom**
### Reference Issue: https://github.com/patternfly/patternfly-demo-app/issues/10

cc @priley86 @andresgalante - Random thought but I just realized that the server is only for building, not serving assets -- which, in retrospect, makes sense because we don't really need one in this case. I was confused about why it still worked when sub-dependencies of PF weren't being installed at all, only PF, using npm3, but it's because we are actually loading the relative paths in the FS and not asking npm to look them up for us. In a real-world scenario, where we'd likely be using a server, this would not work because the latest PF installs its dependencies parallel to its directory under `node_modules`, not in a nested manner, so those paths would no longer exist. Having said that, if we were always asking npm to look up the modules for us without a relative path, it wouldn't matter whether they are nested or not, because of [the way npm looks for modules](https://nodejs.org/api/modules.html#modules_addenda_package_manager_tips).

So, what's happening here is that npm is automatically creating a `node_modules/patternfly/node_modules/` dir for you with sub-dependencies, which I can only attribute to the fact that you have a shrinkwrap file for this version of PF (~3.9.0), whereas 3.10.0 does not and installs sub-dependencies all under the same `node_modules` dir, or parallel to the `node_modules/patternfly` dir. I assumed this was an issue related to npm2 vs npm3, but I'm currently using npm3 and it still seemed to respect the npm2 nested hierarchy of this version of PF. That's a good thing because it means npm2 and npm3 are backwards compatible in some senses (if you have a shrinkwrap file, for instance), but it's a bad thing because it means PF 3.9.0 and 3.10.0 are not backwards compatible for this app or any others out there using relative paths. When using npm, relative paths for third-party dependencies is usually never a good idea unless you have to (e.g. you are building and serving completely static pages not run on a server, so npm only installs but doesn't "look up" modules for you).

Conclusively, I'd imagine you won't ever have a path problem so long as you continue to use the same version of PF for this repo, I believe even if the user is using npm3. The problem arises when a user wants to install the 3.10.x version of PF. They will get the dependencies, but they will be flattened in `node_modules/<sub-dependency>`, which will change the paths referenced in the `src/js/main.js` file.
## Changes:

So, I was left with the following two choices: 1) upgrade to the latest version of PF and update all relative paths referencing a third-party npm dependency; 2) use a server to have npm look up those modules for us dynamically rather than just statically, which would also allow the user to stay with older versions of PF and the paths wouldn't be an issue. Well, their paths would still need to be updated from `('../../node_modules/patternfly/node_modules/bootstrap');` to just `('bootstrap');`, for instance.
- I did both since the first would be a prerequisite to the second option anyway. The second option was just a matter of using Webpack's server that was already running in the background, which comes with BrowserSync, etc. It opens up the app on `localhost:3000` for you automatically, but you can disable that.
- Remove unused dependencies from `package.json`.
- Update npm scripts in `package.json` to use Webpack server and facilitate setup for user.
- Update `README.md` to reflect changes.

No idea why this PR says there are so many more additions than deletions, considering I did more deleting/removing than adding. I did check in the `dist` directory, as that seems to be what you guys were doing for the demo. Please don't hesitate to let me know if I need to make any changes.
## Screenshots

Same as before, just running on the Webpack server, on `localhost:3000`. You can still access the same `index.html` file as before from the `dist` directory.

screenshot 2016-09-14 13 31 54

Thanks in advance!

Rachel

### CODE REVIEW

**Comment by priley86** [comment]
@kahboom, this is fantastic! Thanks so much for the commentary here, and agree completely with your analysis about npm3/npm2 pathing. I was able to pull this branch and run successfully with npm3. As you can see, we are in the process of moving all of our Patternfly projects to npm3/node 4 LTS. It is at the top of our backlog of things to do.

Just a few comments on the changes: 
- I'm OK with removing patternfly-bootstrap-treeview and d3 from `package.json`. It looks like npm3 fixes the d3 dependency challenges we were having, and we haven't quite yet got around to adding a treeview example to this demo app (this should give us some ideas though!). If we remove treeview from the dependency list, please also remove the js reference in `main.js`.
- I like the additions in the README and the npm script modifications. Can we maybe reference npm3 somewhere in the README now (just so people aren't confused)?
- Lastly, if you want to do us a HUGE favor, can you update this demo app to our latest Patternfly release, `3.11.0` (we just released it today)? One thing to note about this is we have moved our `less` files to `dist\less`, so you will also want to change our reference in `custom.less` from:

```
@import (reference) "../../node_modules/patternfly/less/variables.less";
```

to:

```
@import (reference) "../../node_modules/patternfly/dist/less/variables.less";
```

Beyond this, I'm happy to see this merged!

@andresgalante any more thoughts on this?

Thanks a million for this @kahboom! I will be sending some words of praise your way at our next Community Meeting! cc @lhinson

P.S. Can't wait to see what you come up with in your Angular2 app. If you are interested in other demos with web components or React, we've started one [here](https://github.com/priley86/pf-tabs-demo) and will be having some cool announcements about web components pretty soon!

**Comment by priley86** [comment]
- @bleathem. any thoughts?

**Comment by kahboom** [comment]
@priley86 - Anytime; glad I could help! I'll definitely make those changes as soon as I get the chance. Congrats on the release!

Kind of off-topic, but I'm about to comment on this issue I had previously opened up about helping with support for Angular 2: https://github.com/patternfly/angular-patternfly/issues/305

**Comment by kahboom** [comment]
@priley86 - I was just working on these changes now and had a few questions/comments regarding your request for changes:
1. In terms of removing `patternfly-bootstrap-treeview` and `d3` from the `package.json`, they've already been removed from the demo app's `package.json` in this PR. These packages are only installed as a result of the PF `package.json` file, since they are declared as dependencies there. So `d3` and `patternfly-bootstrap-treeview` would need to be removed from the `package.json` on there instead of on here.
2. I was thinking about what comment I would add to the `README.md` regarding npm3, but since we have upgraded the version of PF and are referencing the paths properly now with `require('bootstrap');` for instance, and are using Webpack's server to have npm look up the dependencies properly, then it should work no matter what. The user probably won't know the difference. For example, if I were to say, "Hey, if you use npm2, then sub-dependencies will all be installed in `node_modules` as opposed to `node_modules/patternfly/<subdependency>`," they might be wondering how this would affect them. In reality, it doesn't because even if they were using npm2, the fact that we are not using the version of PF that has a shrinkwrap means that npm will install it in a nested hierarchy if they use npm2, and flattened if they use npm3, but it won't matter because npm will be able to find the module either way now that we are using the Webpack server and having npm "look up" the modules. It will first look in the root of `node_modules` for the `require()`'d dependency, and if it doesn't find it, it will then look within each dependency, to see if it's installed as a sub-dependency. Eventually, it will reach `node_modules/patternfly` and find it in there under its `node_modules` dir. In fact, I even tested it with just opening up the `index.html` file from the `build` dir and it still seems to work fine, probably because the modules are cached. Does that make sense? If you'd still like for me to add some comments, I'd be more than happy to, just let me know what you'd want me to touch on.
3. Done!

I've just pushed up the changes related to upgrading PF to v11.0.

**Comment by priley86** [comment]
fantastic @kahboom! I agree with your analysis and I now understand your reasoning for both # 1 and # 2.

The update to v11.0 looks good as well!

I'm happy to see this merged. 👍 

@andresgalante do you mind reviewing/merging?

We really appreciate this and look forward to hearing how your app development goes with Patternfly/Angular2. W.r.t. to the open issue in Angular P.F., please stay tuned to our ML. We will have a clear roadmap in place after Patternfly f2f next week, and we'll be laying out our development strategy next phase. It's great to hear your team would consider contributions, so I'll be sure to mention this. If you haven't already, you may want to contact Brian Leathem (@bleathem) and share any concerns.

Will be sending major kudos your way for this PR. 🎉

**Comment by kahboom** [comment]
@priley86  - Ah no worries, always glad to help in any way I can. Open source is really amazing. And will do; I'm subscribed to the ML and will keep an eye out. Thanks for welcoming the PR and providing great feedback.

@bleathem - Don't hesitate to give me a shout when the time comes for planning / working on Angular 2 PF. I'm still learning a lot about Angular 2 (worked with 1.x for several years), but I work with it everyday so may be able to provide some insight at one point or another.

**Comment by andresgalante** [comment]
@kahboom Great job, you are awesome! thanks a lot!

I'll merge it 👍

**Pull request merged**
