### PR TITLE
Simplify build process

### LINKED ISSUE #5: CSS files are too heavy
@priley86 patternfly.css is 1.3MB and the /dist folder is 9MB

There seems to be something wrong in the way we build things. If you get stuck with this you can contact @bleathem to bounce some ideas.

### PR DESCRIPTION
**Pull request by priley86**
- Remove webpack less/css optimizations: just reference patternfly dist css. Webpack pathing and greedy font/image inlining is overcomplicating our demo app, and making files too heavy.
- Updates to latest patternfly version `3.7.0`
- Leave sample less file in case consumer wants to append there own less `custom.less`
- Update README
- fixes #5

### CODE REVIEW

**Comment by priley86** [comment]
@bleathem @dtaylor113 @andresgalante this change simplifies our Webpack build and makes our demo app load about a second faster than the original. The page speed score is slightly higher because we have bundled js files. Page speed suggests further inlining scripts/css, however we have already experimented with this and the app slows b/c Webpack inlines so many fonts.

Built changes:
https://rawgit.com/priley86/patternfly-demo-app/build-simplification/dist/index.html

Page Speed:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frawgit.com%2Fpriley86%2Fpatternfly-demo-app%2Fbuild-simplification%2Fdist%2Findex.html&tab=mobile

Original code:
https://rawgit.com/priley86/patternfly-demo-app/old-code/index.html

Page Speed:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frawgit.com%2Fpriley86%2Fpatternfly-demo-app%2Fold-code%2Findex.html&tab=mobile

Are we OK with this change? I think this is a good approach with Webpack for now - until more advanced concepts are introduced to Patternfly.

If so, can we rename this project to `patternfly-webpack-demo` and share with the community?

**Comment by priley86** [comment]
Linking [PTNFLY-1619](https://patternfly.atlassian.net/browse/PTNFLY-1619)

**Comment by bleathem** [comment]
This seems like a good compromise; well don @priley86!  I'm on mobile and not able to run it myself atm, but am happy to see this merged.

+1

**Comment by dtaylor113** [comment]
reviewing now...

**Comment by dtaylor113** [comment]
Hi, cloned this dev branch, ran through steps in README, demo app looks great!

A few questions about the README:

Optimizations

All js references loaded in **js/main.js** will be chunked by webpack and loaded in a single file, dist/main.bundle.js.

**Should this be 'src/js/main.js' ?**

Webpack dev notes

All js dependencies optimized by webpack should be placed in **scripts/main.js**.

**I don't see a scripts dir?**

**Comment by dtaylor113** [comment]
Should the 'Optimizations' section be renamed 'Extending The Demo App' ?

Under that section I'd like to see three sub-sections for how to add my own Javascript, HTML, and LESS files.   

i don't think you need to call out instructions pertaining to webpack, just keep it about how one extends the demo app.

Thanks,
- Dave

**Comment by dtaylor113** [comment]
May want to document that if you add a new html file under src/html, you have to rerun 'npm start' in order for it to show up in browser.

**Comment by priley86** [comment]
@dtaylor113 thanks for all the help reviewing, and I like the suggestions! I'll update the README and rebase shortly.

**Comment by priley86** [comment]
@dtaylor113 I've updated the README in this PR (you can see it [here](https://github.com/priley86/patternfly-demo-app/tree/build-simplification)). Updated the content with your suggestions and removed a bit about Webpack HMR (figured this was extraneous info).

@bleathem let me know if you have any further comments after reviewing further 🔔

**Comment by priley86** [comment]
@dlabrecq @dgutride would appreciate you guys weighing in here as well - let me know if there is anything else you'd like changed this sprint before we merge this PR.

**Comment by bleathem** [comment]
Do we want to be including the `/dist` folder?

**Comment by priley86** [comment]
@bleathem good question - i am open to mimicking our travis setup in [patternfly](https://github.com/patternfly/patternfly) if we think it's a good idea for consumers. I'll try to set something up in another PR if you think it wise.

**Comment by bleathem** [comment]
+1 for another PR to remove dist.  I like the changes @dtaylor113 suggested.  This PR looks good to merge.

:+1:

**Comment by priley86** [comment]
@dtaylor113 are you OK with merging this PR? I think we should make note of removing `dist` in a future story for this demo app.

**Comment by dtaylor113** [comment]
Ok, LGTM

**Pull request merged**
